import { Hotline } from '@/types'

const REVIEW_DATE = '2026-06-21'

export const BD_HOTLINES: Hotline[] = [
  {
    id: '1',
    name: 'National Emergency',
    number: '999',
    description: 'Police, fire, ambulance - 24/7 national emergency line',
    category: 'police',
    available24h: true,
    sourceName: 'Bangladesh Police',
    sourceUrl: 'https://www.police.gov.bd/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
  {
    id: '2',
    name: 'Women & Child Abuse Helpline',
    number: '10921',
    description:
      'Ministry of Women & Children Affairs - violence and abuse support',
    category: 'domestic_violence',
    available24h: true,
    sourceName: 'Ministry of Women and Children Affairs',
    sourceUrl: 'https://mowca.gov.bd/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
  {
    id: '3',
    name: 'National Child Helpline',
    number: '1098',
    description: 'Child abuse, trafficking, exploitation - report and support',
    category: 'child_protection',
    available24h: true,
    sourceName: 'Ministry of Women and Children Affairs',
    sourceUrl: 'https://mowca.gov.bd/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
  {
    id: '4',
    name: 'Ambulance',
    number: '199',
    description: 'National ambulance service',
    category: 'medical',
    available24h: true,
    sourceName: 'Bangladesh health services',
    sourceUrl: 'https://www.dghs.gov.bd/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
  {
    id: '5',
    name: 'Kaan Pete Roi (Mental Health)',
    number: '01779-554391',
    description: 'Emotional support and mental health helpline',
    category: 'mental_health',
    available24h: false,
    sourceName: 'Kaan Pete Roi',
    sourceUrl: 'https://www.kaanpeteroi.org/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
  {
    id: '6',
    name: 'BLAST Legal Aid',
    number: '01713-130880',
    description:
      'Bangladesh Legal Aid and Services Trust - free legal help for women',
    category: 'domestic_violence',
    available24h: false,
    sourceName: 'Bangladesh Legal Aid and Services Trust',
    sourceUrl: 'https://blast.org.bd/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
  {
    id: '7',
    name: 'BNWLA Helpline',
    number: '01190-003007',
    description: 'Bangladesh National Women Lawyers Association',
    category: 'domestic_violence',
    available24h: false,
    sourceName: 'Bangladesh National Women Lawyers Association',
    sourceUrl: 'https://bnwla.org/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
  {
    id: '8',
    name: 'Fire Service',
    number: '102',
    description: 'National fire service',
    category: 'medical',
    available24h: true,
    sourceName: 'Fire Service and Civil Defence',
    sourceUrl: 'https://fireservice.gov.bd/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
]
