import { BundledSafeSpace } from '@/types'

const REVIEW_DATE = '2026-06-21'

export const REVIEWED_SAFE_SPACES: BundledSafeSpace[] = [
  {
    id: 'dhaka_police_victim_support',
    name: 'Police Victim Support Center',
    type: 'police',
    area: 'Dhaka',
    location: { latitude: 23.7337, longitude: 90.3955 },
    phone: '999',
    hours: '24/7 hotline support',
    verified: true,
    sourceName: 'Bangladesh Police',
    sourceUrl: 'https://www.police.gov.bd/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
  {
    id: 'women_child_abuse_helpline',
    name: 'Women and Child Abuse Helpline',
    type: 'childcare',
    area: 'Bangladesh-wide',
    location: { latitude: 23.8103, longitude: 90.4125 },
    phone: '10921',
    hours: '24/7 hotline support',
    verified: true,
    sourceName: 'Ministry of Women and Children Affairs',
    sourceUrl: 'https://mowca.gov.bd/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
  {
    id: 'child_helpline_1098',
    name: 'National Child Helpline',
    type: 'childcare',
    area: 'Bangladesh-wide',
    location: { latitude: 23.8103, longitude: 90.4125 },
    phone: '1098',
    hours: '24/7 hotline support',
    verified: true,
    sourceName: 'Ministry of Women and Children Affairs',
    sourceUrl: 'https://mowca.gov.bd/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
  {
    id: 'blast_legal_aid',
    name: 'BLAST Legal Aid',
    type: 'legal',
    area: 'Dhaka',
    location: { latitude: 23.7509, longitude: 90.3921 },
    phone: '01713-130880',
    hours: 'Office hours',
    verified: true,
    sourceName: 'Bangladesh Legal Aid and Services Trust',
    sourceUrl: 'https://blast.org.bd/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
  {
    id: 'bnwla_helpline',
    name: 'BNWLA Helpline',
    type: 'legal',
    area: 'Dhaka',
    location: { latitude: 23.761, longitude: 90.3748 },
    phone: '01190-003007',
    hours: 'Office hours',
    verified: true,
    sourceName: 'Bangladesh National Women Lawyers Association',
    sourceUrl: 'https://bnwla.org/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
  {
    id: 'kaan_pete_roi',
    name: 'Kaan Pete Roi',
    type: 'counseling',
    area: 'Dhaka',
    location: { latitude: 23.7806, longitude: 90.4072 },
    phone: '01779-554391',
    hours: 'Listed support hours',
    verified: true,
    sourceName: 'Kaan Pete Roi',
    sourceUrl: 'https://www.kaanpeteroi.org/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
  {
    id: 'dhaka_medical_college_hospital',
    name: 'Dhaka Medical College Hospital',
    type: 'hospital',
    area: 'Dhaka',
    location: { latitude: 23.7226, longitude: 90.3994 },
    phone: '199',
    hours: '24/7 emergency care',
    verified: true,
    sourceName: 'Directorate General of Health Services',
    sourceUrl: 'https://www.dghs.gov.bd/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
  {
    id: 'dhaka_shelter_referral',
    name: 'Shelter Referral Desk',
    type: 'shelter',
    area: 'Dhaka',
    location: { latitude: 23.8103, longitude: 90.4125 },
    phone: '10921',
    hours: '24/7 hotline support',
    verified: true,
    sourceName: 'Ministry of Women and Children Affairs',
    sourceUrl: 'https://mowca.gov.bd/',
    verificationStatus: 'reviewed',
    lastVerifiedAt: REVIEW_DATE,
  },
]
